In [1]:
import pandas as pd

# 1. Data Importing 

- pd.read_csv()

- pd.read_table()

- pd.read_excel()

- pd.read_sql()

- pd.read_json()

- pd.read_html()

# 2. Data Cleaning

- pd.fillna()
- pd.dropna()
- pd.sort_values()
- pd.fillna()
- pd.groupby()
- pd.join()
- pd.append()

# 3. Data Statistics

- pd.head()
- pd.tail() 
- pd.info()
- pd.describe()
- pd.mean()
- pd.median()
- pd.count()
- pd.std()
- pd.max()
- pd.min()
- pd.unique()

In [2]:
Dataset = pd.read_csv("Data_December.csv")
Dataset

,Date No:,Date,Code,Customer,Employee Name,Group,Item Code,Item Group Name,Category,Category_N,Brand,Item Name,O/UN-O,Serial,Qty,Price,Total,I_Group
0,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,5616,Power & Smart Tech,Power Adapter,Power Adapter,Anker,Anker PowerPort III 20W Cube,Un-Official,AGL2023RI2800,1,1150,1150.0,Power Tech
1,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,912,Apple Accessories,Data Cable,Data Cable,Apple,Apple USB-C to Lightning Cable 1m - Non Author...,Un-Official,AGL2023RI2012,1,1000,1000.0,Power Tech
2,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,22672,Used Devices,iPhone - Used,iPhone - Used,Apple,iPhone 11 128GB Green e-Sim Slim Box (Used),Un-Official,LL/A-356460901338877 (A),1,47500,47500.0,Devices
3,1,12/1/2023,S-01-12-2023-274340,Sakib,Arif - 007,B.City,19858,Power & Smart Tech,Power Adapter,Power Adapter,Anker,Anker 511 Charger Nano 3 - 30W - White,Un-Official,AGL2023RI1370,1,1650,1650.0,Power Tech
4,1,12/1/2023,S-01-12-2023-274339,Major Parvej,Mehedi - 165,B.City,3037,Outfits,Macbook Cover,Macbook Cover,WiWu,WiWU Keyboard Protector for MacBook - Air 13.3...,Un-Official,AGL2023RM0069,1,850,850.0,N|A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9759,31,12/31/2023,S-31-12-2023-283715,Shuvo,Tanver - 321,TS,23338,Outfits,Phone Screen Protector,Phone Screen Protector,Anank,Anank 2.5D Anti-Blue Glass Screen Protector fo...,Un-Official,NaN,1,1050,1050.0,N|A
9760,31,12/31/2023,S-31-12-2023-283715,Shuvo,Tanver - 321,TS,2574,Outfits,Polly / Sticker,Polly / Sticker,NaN,Matte Polly - 7 inch,Un-Official,NaN,1,200,200.0,N|A
9761,31,12/31/2023,S-31-12-2023-283209,Mohammad Fahad,Nur - TS,TS,22227,New Devices,Nokia Mobile,Nokia Mobile,Nokia,Nokia 6310 Dual Sim - Green,Un-Official,IN/D-357703386079832,1,6000,6000.0,Devices
9762,31,12/31/2023,S-31-12-2023-280832,Rubaiya Obayed,Ashish - 014,TS,23354,New Devices,iPhone,iPhone,Apple,iPhone 15 256GB Green e-Sim (New),Un-Official,ZP/A-356942576670775,1,127000,127000.0,Devices
9763,31,12/31/2023,S-31-12-2023-277692,Musfiq,Arif - 007,B.City,23965,Used Devices,honor Mobile - Used,honor Mobile - Used,Honor,HONOR X9b 5G 12/256GB Dual Sim Titanium Silver...,Un-Official,868984064208719 (A),1,27000,26500.0,N|A

In [3]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9764 entries, 0 to 9763
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date No:         9764 non-null   int64
 1   Date             9764 non-null   object
 2   Code             9764 non-null   object
 3   Customer         9763 non-null   object
 4   Employee Name    9764 non-null   object
 5   Group            9764 non-null   object
 6   Item Code        9764 non-null   int64
 7   Item Group Name  9764 non-null   object
 8   Category         9764 non-null   object
 9   Category_N       9764 non-null   object
 10  Brand            8753 non-null   object
 11  Item Name        9764 non-null   object
 12  O/UN-O           9764 non-null   object
 13  Serial           6933 non-null   object
 14  Qty              9764 non-null   int64
 15  Price            9764 non-null   int64
 16  Total            9764 non-null   float64
 17  I_Group          9764 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 1.3+ MB

In [4]:
Dataset.head()

,Date No:,Date,Code,Customer,Employee Name,Group,Item Code,Item Group Name,Category,Category_N,Brand,Item Name,O/UN-O,Serial,Qty,Price,Total,I_Group
0,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,5616,Power & Smart Tech,Power Adapter,Power Adapter,Anker,Anker PowerPort III 20W Cube,Un-Official,AGL2023RI2800,1,1150,1150.0,Power Tech
1,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,912,Apple Accessories,Data Cable,Data Cable,Apple,Apple USB-C to Lightning Cable 1m - Non Author...,Un-Official,AGL2023RI2012,1,1000,1000.0,Power Tech
2,1,12/1/2023,S-01-12-2023-274341,Abdul Alim,Zahid - 217,B.City,22672,Used Devices,iPhone - Used,iPhone - Used,Apple,iPhone 11 128GB Green e-Sim Slim Box (Used),Un-Official,LL/A-356460901338877 (A),1,47500,47500.0,Devices
3,1,12/1/2023,S-01-12-2023-274340,Sakib,Arif - 007,B.City,19858,Power & Smart Tech,Power Adapter,Power Adapter,Anker,Anker 511 Charger Nano 3 - 30W - White,Un-Official,AGL2023RI1370,1,1650,1650.0,Power Tech
4,1,12/1/2023,S-01-12-2023-274339,Major Parvej,Mehedi - 165,B.City,3037,Outfits,Macbook Cover,Macbook Cover,WiWu,WiWU Keyboard Protector for MacBook - Air 13.3...,Un-Official,AGL2023RM0069,1,850,850.0,N|A

In [5]:
Dataset.tail()

,Date No:,Date,Code,Customer,Employee Name,Group,Item Code,Item Group Name,Category,Category_N,Brand,Item Name,O/UN-O,Serial,Qty,Price,Total,I_Group
9759,31,12/31/2023,S-31-12-2023-283715,Shuvo,Tanver - 321,TS,23338,Outfits,Phone Screen Protector,Phone Screen Protector,Anank,Anank 2.5D Anti-Blue Glass Screen Protector fo...,Un-Official,NaN,1,1050,1050.0,N|A
9760,31,12/31/2023,S-31-12-2023-283715,Shuvo,Tanver - 321,TS,2574,Outfits,Polly / Sticker,Polly / Sticker,NaN,Matte Polly - 7 inch,Un-Official,NaN,1,200,200.0,N|A
9761,31,12/31/2023,S-31-12-2023-283209,Mohammad Fahad,Nur - TS,TS,22227,New Devices,Nokia Mobile,Nokia Mobile,Nokia,Nokia 6310 Dual Sim - Green,Un-Official,IN/D-357703386079832,1,6000,6000.0,Devices
9762,31,12/31/2023,S-31-12-2023-280832,Rubaiya Obayed,Ashish - 014,TS,23354,New Devices,iPhone,iPhone,Apple,iPhone 15 256GB Green e-Sim (New),Un-Official,ZP/A-356942576670775,1,127000,127000.0,Devices
9763,31,12/31/2023,S-31-12-2023-277692,Musfiq,Arif - 007,B.City,23965,Used Devices,honor Mobile - Used,honor Mobile - Used,Honor,HONOR X9b 5G 12/256GB Dual Sim Titanium Silver...,Un-Official,868984064208719 (A),1,27000,26500.0,N|A

In [6]:
Dataset.describe()

          Date No:     Item Code          Qty          Price          Total
count  9764.000000   9764.000000  9764.000000    9764.000000    9764.000000
mean     16.150348  14712.075072     1.039226   21413.645535   21669.316364
std       9.157589   9445.562770     0.492905   41689.791203   42374.782505
min       1.000000     19.000000     1.000000       1.000000       1.000000
25%       8.000000   4209.000000     1.000000    1200.000000    1200.000000
50%      16.000000  20530.000000     1.000000    2900.000000    3000.000000
75%      24.000000  22882.000000     1.000000   15800.000000   16025.000000
max      31.000000  24148.000000    28.000000  345000.000000  345000.000000

In [7]:
Dataset["Price"].mean()

21413.64553461696

In [8]:
Dataset["Price"].median()

2900.0

In [9]:
Dataset["I_Group"].unique()

array(['Power Tech', 'Devices', 'N|A', 'Smart Tech', 'Sound Tech',
       'Smart Watch'], dtype=object)

In [10]:
Dataset["Price"].std()

41689.791203045774

In [11]:
Dataset["Price"].min()

1

In [12]:
Dataset["Price"].max()

345000